version: '3'
services:
  web:
    build: web/.
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    ports:
      - 8000-8005:8000

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx:/var/log/nginx
    ports:
      - 8989:8989
    depends_on:
      - web
    restart: always

